import type { DemoRecording } from "../types";

/** THE PROOF, on screen. No sampled past hackathon winner shipped this. */
export function ScoreCard({ scorecard }: { scorecard: DemoRecording["scorecard"] }) {
  const rows: [string, string][] = [
    ["Agent detection rate", `${Math.round(scorecard.detection_rate * 100)}%`],
    ["Agent false positive rate", `${Math.round(scorecard.false_positive_rate * 100)}%`],
    ["Threshold-alerting baseline detection rate", `${Math.round(scorecard.baseline_detection_rate * 100)}%`],
  ];

  return (
    <div style={{ padding: 16, borderRadius: 8, background: "#12151a", border: "1px solid #2a2f37" }}>
      <div style={{ fontSize: 12, color: "#9aa4b2", textTransform: "uppercase", letterSpacing: 1, marginBottom: 10 }}>
        Eval scorecard — regenerated by eval/harness.py, not hand-written
      </div>
      {rows.map(([label, value]) => (
        <div key={label} style={{ display: "flex", justifyContent: "space-between", padding: "4px 0", fontSize: 13 }}>
          <span style={{ color: "#c3c9d1" }}>{label}</span>
          <span style={{ fontVariantNumeric: "tabular-nums" }}>{value}</span>
        </div>
      ))}
      <div
        style={{
          marginTop: 12,
          padding: "10px 12px",
          borderRadius: 6,
          background: "#1c1608",
          border: "1px solid #4a3a12",
        }}
      >
        <div style={{ fontSize: 12, color: "#f4b942" }}>Defects the baseline missed that vision caught</div>
        <div style={{ fontSize: 26, fontWeight: 700, color: "#f4b942" }}>{scorecard.vision_only_catches}</div>
      </div>
    </div>
  );
}
