"""Copies real rendered frames from backlot/frames_local/ into
control-room/public/frames/ so the UI can show the actual broken picture,
not just prose describing it — and writes a MANIFEST.json with a sha256 of
each file plus its source job/condition, so "this is a real render" is
checkable rather than asserted (verify with `shasum -a 256`).

frames_local/ is gitignored (it's the raw render output, regenerated by
backlot/render_eval_conditions.py); the copies under control-room/public/
are not, so a small, fixed set of frames the UI actually needs ships with
the repo without requiring a judge to run Blender to see them.

Usage:
    python backlot/export_ui_frames.py
"""
from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FRAMES_LOCAL = REPO_ROOT / "backlot" / "frames_local"
DEST_DIR = REPO_ROOT / "control-room" / "public" / "frames"
JOB_MAP_PATH = REPO_ROOT / "backlot" / "eval_job_map.json"

# Every frame the UI needs to show, and why. Keep this list small and
# deliberate — it's the set of images that actually ship in the repo, not
# an automatic dump of every rendered frame.
FRAMES = [
    {
        "job_id": "job-seq042-sh0420",
        "filename": "frame_0185.png",
        "condition": "low_samples",
        "note": "The frame EyesAgent's recorded finding names verbatim — denoiser fireflies, job exits 0, metrics stay green.",
    },
    {
        "job_id": "eval-clean-000",
        "filename": "frame_0001.png",
        "condition": "clean",
        "note": "Same pipeline, a genuinely clean render, for the VisionProof side-by-side.",
    },
    {
        "job_id": "eval-low_samples-003",
        "filename": "frame_0001.png",
        "condition": "low_samples",
        "note": "A second real defective render, distinct from job-seq042-sh0420, for the VisionProof side-by-side.",
    },
]


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def main() -> None:
    job_map: dict[str, str] = json.loads(JOB_MAP_PATH.read_text()) if JOB_MAP_PATH.exists() else {}
    DEST_DIR.mkdir(parents=True, exist_ok=True)

    manifest = []
    for entry in FRAMES:
        src = FRAMES_LOCAL / entry["job_id"] / entry["filename"]
        if not src.exists():
            raise FileNotFoundError(
                f"{src} not found — render it first (backlot/render_eval_conditions.py or "
                f"backlot/worker/render_worker.py --job-id {entry['job_id']})"
            )
        dest_name = f"{entry['job_id']}__{entry['filename']}"
        dest = DEST_DIR / dest_name
        shutil.copyfile(src, dest)

        manifest.append(
            {
                "job_id": entry["job_id"],
                "source_condition": job_map.get(entry["job_id"], entry["condition"]),
                "source_path": str(src.relative_to(REPO_ROOT)),
                "public_path": f"/frames/{dest_name}",
                "sha256": sha256_of(dest),
                "note": entry["note"],
            }
        )
        print(f"copied {src} -> {dest} (sha256 {manifest[-1]['sha256'][:12]}...)")

    (DEST_DIR / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"wrote {DEST_DIR / 'MANIFEST.json'}")


if __name__ == "__main__":
    main()
